/leader/joint_states:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
/follower/joint_states:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
/camera1/image_raw/compressed:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
/camera2/image_raw/compressed:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
/follower/joint_trajectory_controller/joint_trajectory:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10
