<template>
  <div class="deployment-workspace">
    <section class="deploy-config" aria-label="部署模型">
      <div class="pane-heading"><div><p class="eyebrow">DEPLOY MODEL</p><h3>部署模型</h3></div><span>local-robot</span></div>
      <div class="target-state" :class="{ healthy: target?.healthy }"><small>本机机器人</small><strong>{{ target?.current ? `${target.current.modelName} v${target.current.modelVersion}` : "尚未部署" }}</strong><span>{{ target?.current ? target.healthy ? "产物指针正常" : "产物指针异常" : "等待选择生产模型" }}</span></div>
      <div class="form-grid"><label>Production 模型<select v-model="form.modelId"><option value="" disabled>选择模型</option><option v-for="model in productionModels" :key="model.id" :value="model.id">{{ model.name }} v{{ model.version }}{{ model.evaluation.successRate == null ? "" : ` · ${formatPercent(model.evaluation.successRate)}` }}</option></select></label><label>操作人<input v-model.trim="form.actor" maxlength="80" /></label><label>部署备注<textarea v-model.trim="form.notes" maxlength="500" rows="3"></textarea></label></div>
      <div v-if="selectedModel" class="model-gate"><div><span>评估任务</span><strong>{{ selectedModel.evaluation.jobs }}</strong></div><div><span>有效 Episodes</span><strong>{{ selectedModel.evaluation.success + selectedModel.evaluation.failure }}</strong></div><div><span>成功率</span><strong>{{ formatPercent(selectedModel.evaluation.successRate) }}</strong></div><p v-if="selectedModel.evaluation.successRate == null">该模型尚无有效评估结果，部署后应先进行受控验证。</p></div>
      <button class="primary" :disabled="deploying || !selectedModel || target?.current?.modelId === selectedModel.id" @click="deployModel">{{ deploying ? "校验并部署中…" : target?.current?.modelId === selectedModel?.id ? "当前已部署" : "部署到本机机器人" }}</button>
      <p class="deploy-hint">部署仅原子切换模型目录，不会启动推理或驱动机械臂。</p>
    </section>

    <section class="revision-pane" aria-label="部署历史">
      <div class="pane-heading"><div><p class="eyebrow">DEPLOYMENT HISTORY</p><h3>部署历史</h3></div><span>{{ target?.revisions.length || 0 }} 个修订</span></div>
      <div v-if="target?.current" class="current-revision"><div><small>当前修订</small><strong>{{ target.current.id }}</strong></div><span>{{ formatDate(target.current.deployedAt) }} · {{ target.current.deployedBy }}</span><code>{{ target.linkPath }}</code></div>
      <div v-if="target?.revisions.length" class="revision-list"><article v-for="revision in target.revisions" :key="revision.id" :class="{ active: revision.status === 'active' }"><div><span><strong>{{ revision.modelName }} v{{ revision.modelVersion }}</strong><small>{{ revision.action === "rollback" ? "回滚部署" : "正常部署" }} · {{ formatDate(revision.deployedAt) }}</small></span><em>{{ revision.status === "active" ? "当前" : "历史" }}</em></div><code :title="revision.sha256">{{ revision.sha256.slice(0, 16) }}…</code><p>{{ revision.notes || "无部署备注" }}</p><button v-if="revision.status !== 'active'" :disabled="rollingBack" @click="rollback(revision.id)">回滚到此修订</button></article></div>
      <div v-else class="empty">部署后会在这里保留不可变修订历史</div>
    </section>

    <section class="incident-pane" aria-label="推理异常">
      <div class="pane-heading"><div><p class="eyebrow">INFERENCE INCIDENTS</p><h3>推理异常</h3></div><span>{{ openIncidents }} 未关闭</span></div>
      <div class="incident-form"><div><label>严重程度<select v-model="incidentForm.severity"><option value="warning">警告</option><option value="error">错误</option><option value="critical">严重</option></select></label><label>类型<select v-model="incidentForm.category"><option v-for="item in incidentCategories" :key="item.value" :value="item.value">{{ item.label }}</option></select></label></div><label>异常描述<textarea v-model.trim="incidentForm.description" maxlength="1000" rows="3"></textarea></label><button :disabled="!target?.current || !incidentForm.description || reporting" @click="reportIncident">记录异常</button></div>
      <div v-if="incidents.length" class="incident-list"><article v-for="incident in incidents" :key="incident.id" :class="[incident.severity, incident.status]"><header><span><strong>{{ categoryText(incident.category) }}</strong><small>{{ formatDate(incident.reportedAt) }} · {{ incident.reportedBy }}</small></span><em>{{ incident.status === "open" ? severityText(incident.severity) : "已关闭" }}</em></header><p>{{ incident.description }}</p><div v-if="incident.status === 'open'" class="resolve-row"><input v-model.trim="resolutions[incident.id]" maxlength="1000" placeholder="处理结论" /><button :disabled="!resolutions[incident.id]" @click="resolveIncident(incident.id)">关闭</button></div><small v-else class="resolution">处理结论：{{ incident.resolution }}</small></article></div>
      <div v-else class="empty">尚无推理异常记录</div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from "vue";

interface EvaluationMetric { jobs: number; episodes: number; success: number; failure: number; successRate: number | null }
interface Model { id: string; name: string; version: number; stage: string; evaluation: EvaluationMetric }
interface Revision { id: string; modelId: string; modelName: string; modelVersion: number; sha256: string; action: "deploy" | "rollback"; status: "active" | "superseded"; deployedAt: string; deployedBy: string; notes: string }
interface Target { id: string; name: string; currentRevisionId: string | null; revisions: Revision[]; current: Revision | null; linkPath: string; healthy: boolean; openIncidents: number }
interface Incident { id: string; targetId: string; revisionId: string | null; modelId: string | null; severity: "warning" | "error" | "critical"; category: string; description: string; status: "open" | "resolved"; reportedAt: string; reportedBy: string; resolvedAt: string | null; resolution: string }

const emit = defineEmits<{ error: [message: string] }>();
const models = ref<Model[]>([]); const targets = ref<Target[]>([]); const incidents = ref<Incident[]>([]); const deploying = ref(false); const rollingBack = ref(false); const reporting = ref(false);
const resolutions = reactive<Record<string, string>>({});
const form = reactive({ modelId: "", actor: "本地用户", notes: "" });
const incidentForm = reactive({ severity: "warning" as Incident["severity"], category: "jitter", description: "" });
const incidentCategories = [{ value: "jitter", label: "机械臂抖动" }, { value: "action_offset", label: "动作偏移" }, { value: "collision", label: "碰撞" }, { value: "camera", label: "相机异常" }, { value: "latency", label: "推理延迟" }, { value: "hardware", label: "硬件异常" }, { value: "other", label: "其他" }];
const target = computed(() => targets.value.find((item) => item.id === "local-robot") || null);
const productionModels = computed(() => models.value.filter((model) => model.stage === "production"));
const selectedModel = computed(() => productionModels.value.find((model) => model.id === form.modelId) || productionModels.value[0] || null);
const openIncidents = computed(() => incidents.value.filter((incident) => incident.status === "open").length);

async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, init); const data = await response.json(); if (!response.ok || data.ok === false) throw new Error(data.error || `HTTP ${response.status}`); return data; }
async function refreshAll() { try { const [modelData, deploymentData] = await Promise.all([requestJson("/api/training/models"), requestJson("/api/training/deployments")]); models.value = modelData.models || []; targets.value = deploymentData.targets || []; incidents.value = deploymentData.incidents || []; if (!form.modelId && productionModels.value.length) form.modelId = productionModels.value[0].id; } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
async function deployModel() { if (!selectedModel.value || deploying.value) return; deploying.value = true; try { await requestJson("/api/training/deployments/local-robot/deploy", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ modelId: selectedModel.value.id, actor: form.actor, notes: form.notes }) }); await refreshAll(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } finally { deploying.value = false; } }
async function rollback(revisionId: string) { if (rollingBack.value) return; rollingBack.value = true; try { await requestJson("/api/training/deployments/local-robot/rollback", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ revisionId, actor: form.actor, notes: `回滚到 ${revisionId}` }) }); await refreshAll(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } finally { rollingBack.value = false; } }
async function reportIncident() { if (!incidentForm.description || reporting.value) return; reporting.value = true; try { await requestJson("/api/training/deployments/local-robot/incidents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...incidentForm, actor: form.actor }) }); incidentForm.description = ""; await refreshAll(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } finally { reporting.value = false; } }
async function resolveIncident(id: string) { try { await requestJson(`/api/training/incidents/${encodeURIComponent(id)}/resolve`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resolution: resolutions[id] }) }); resolutions[id] = ""; await refreshAll(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
function formatPercent(value: number | null) { return value == null ? "-" : `${(value * 100).toFixed(1)}%`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
function categoryText(category: string) { return incidentCategories.find((item) => item.value === category)?.label || category; }
function severityText(severity: Incident["severity"]) { return ({ warning: "警告", error: "错误", critical: "严重" })[severity]; }
onMounted(() => { void refreshAll(); });
</script>

<style scoped>
.deployment-workspace { display: grid; grid-template-columns: 310px minmax(380px,1fr) 360px; min-height: calc(100vh - 225px); border: 1px solid rgba(151,188,222,.15); border-top: 0; background: #0d1928; }.deploy-config,.revision-pane,.incident-pane { min-width: 0; padding: 14px; }.deploy-config,.revision-pane { border-right: 1px solid rgba(151,188,222,.13); }.pane-heading { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; margin-bottom: 14px; }.pane-heading h3 { margin-top: 2px; font-size: 13px; }.pane-heading > span { color: #70899c; font-size: 8px; }.eyebrow { color: #78a9c6; font-size: 9px; font-weight: 700; letter-spacing: 1px; }.target-state { display: grid; gap: 4px; margin-bottom: 12px; padding: 10px; border-left: 3px solid #718494; background: #101c29; }.target-state.healthy { border-color: #54c994; background: #10251f; }.target-state small,.target-state span { color: #6f8799; font-size: 8px; }.target-state strong { color: #dce8ef; font-size: 12px; }.form-grid { display: grid; gap: 9px; }.form-grid label,.incident-form label { display: grid; gap: 4px; color: #8299aa; font-size: 8px; }.form-grid input,.form-grid select,.form-grid textarea,.incident-form input,.incident-form select,.incident-form textarea,.resolve-row input { width: 100%; min-width: 0; padding: 8px; border: 1px solid #29435f; border-radius: 4px; outline: 0; resize: vertical; background: #091522; color: #d9e6ed; font-size: 9px; }.model-gate { display: grid; grid-template-columns: repeat(3,1fr); margin-top: 10px; border: 1px solid rgba(151,188,222,.12); }.model-gate div { display: grid; gap: 3px; padding: 8px; border-right: 1px solid rgba(151,188,222,.08); }.model-gate div:nth-child(3) { border-right: 0; }.model-gate span,.model-gate p { color: #687f91; font-size: 7px; }.model-gate strong { color: #b9ccd7; font: 10px ui-monospace,monospace; }.model-gate p { grid-column: 1/-1; margin: 0; padding: 7px; border-top: 1px solid rgba(151,188,222,.08); color: #d0af6b; }.primary,.incident-form > button { width: 100%; margin-top: 10px; padding: 9px; border: 0; border-radius: 4px; cursor: pointer; background: #64c9e8; color: #07131c; font-size: 9px; font-weight: 650; }.primary:disabled,.incident-form button:disabled { cursor: not-allowed; opacity: .4; }.deploy-hint { color: #60798b; font-size: 8px; line-height: 1.5; }
.current-revision { display: grid; grid-template-columns: 1fr auto; gap: 5px 12px; padding: 10px; border-left: 3px solid #54c994; background: #10251f; }.current-revision div { display: grid; gap: 3px; }.current-revision small,.current-revision span,.current-revision code { color: #718e80; font-size: 7px; }.current-revision strong { color: #b9dac8; font-size: 10px; }.current-revision code { grid-column: 1/-1; overflow-wrap: anywhere; }.revision-list { margin-top: 10px; }.revision-list article { position: relative; padding: 10px; border: 1px solid rgba(151,188,222,.11); border-bottom: 0; background: #091522; }.revision-list article:last-child { border-bottom: 1px solid rgba(151,188,222,.11); }.revision-list article.active { border-left: 3px solid #54c994; }.revision-list article > div { display: flex; justify-content: space-between; gap: 8px; }.revision-list article span { display: grid; gap: 3px; }.revision-list article strong { color: #b7c9d4; font-size: 9px; }.revision-list article small,.revision-list article code,.revision-list article p { color: #657e91; font-size: 7px; }.revision-list article em { padding: 3px 5px; border-radius: 3px; color: #8196a5; background: #263541; font-size: 7px; font-style: normal; }.revision-list article.active em { color: #65daa4; background: #173a31; }.revision-list article code { display: block; margin-top: 7px; }.revision-list article p { margin: 5px 0; }.revision-list article > button { padding: 5px 7px; border: 1px solid #38536a; border-radius: 3px; cursor: pointer; background: #101f2e; color: #8fc8dc; font-size: 7px; }
.incident-form { padding: 10px; border: 1px solid rgba(151,188,222,.12); background: #091522; }.incident-form > div { display: grid; grid-template-columns: 1fr 1fr; gap: 7px; margin-bottom: 8px; }.incident-list { margin-top: 10px; }.incident-list article { padding: 9px; border: 1px solid rgba(151,188,222,.1); border-left: 3px solid #e1bf76; border-bottom: 0; background: #091522; }.incident-list article:last-child { border-bottom: 1px solid rgba(151,188,222,.1); }.incident-list article.error { border-left-color: #e8798a; }.incident-list article.critical { border-left-color: #ff536a; background: #1e1117; }.incident-list article.resolved { border-left-color: #637686; opacity: .78; }.incident-list header { display: flex; justify-content: space-between; gap: 8px; }.incident-list header span { display: grid; gap: 3px; }.incident-list strong { color: #b8c9d3; font-size: 9px; }.incident-list small,.incident-list p { color: #698194; font-size: 7px; }.incident-list em { padding: 3px 5px; border-radius: 3px; color: #e1bf76; background: #382f1d; font-size: 7px; font-style: normal; }.incident-list article.error em,.incident-list article.critical em { color: #ff91a0; background: #3a2028; }.incident-list p { margin: 7px 0; line-height: 1.5; }.resolve-row { display: grid; grid-template-columns: 1fr auto; gap: 5px; }.resolve-row input { padding: 6px; font-size: 8px; }.resolve-row button { border: 0; border-radius: 3px; cursor: pointer; background: #294b60; color: #b5d6e5; font-size: 8px; }.resolution { display: block; padding-top: 5px; border-top: 1px solid rgba(151,188,222,.08); }.empty { display: grid; place-items: center; min-height: 180px; color: #667f92; font-size: 9px; }
@container (max-width: 1150px) { .deployment-workspace { grid-template-columns: 300px 1fr; }.deploy-config { grid-row: 1/span 2; }.revision-pane { border-right: 0; border-bottom: 1px solid rgba(151,188,222,.13); }.incident-pane { grid-column: 2; } }
@container (max-width: 720px) { .deployment-workspace { display: block; }.deploy-config,.revision-pane { border-right: 0; border-bottom: 1px solid rgba(151,188,222,.13); }.model-gate { grid-template-columns: 1fr 1fr 1fr; } }
</style>
