<template>
  <div class="evaluation-layout">
    <section class="evaluation-config" aria-label="新建模型评估任务">
      <div class="pane-heading"><div><p class="eyebrow">NEW EVALUATION</p><h3>新建评估</h3></div><span>实时推理录制</span></div>
      <div v-if="!models.length" class="notice">请先从已完成训练的 Checkpoint 登记模型。</div>
      <div class="form-grid">
        <label>评估名称<input v-model.trim="form.name" maxlength="80" placeholder="eval_pick_place_v1" /></label>
        <label>模型<select v-model="form.modelId" @change="applyModelDefaults"><option value="" disabled>选择已登记模型</option><option v-for="model in models" :key="model.id" :value="model.id">{{ model.name }} v{{ model.version }} · {{ modelStage(model.stage) }}</option></select></label>
        <label>评估 Dataset<input v-model.trim="form.evalDataset" maxlength="64" placeholder="eval_pick_place_v1" /></label>
        <label>任务描述<textarea v-model.trim="form.task" maxlength="200" rows="2" placeholder="Put lego brick into the transparent box"></textarea></label>
        <div class="two-columns"><label>Follower 串口<select v-model="form.followerPort"><option v-for="port in ports" :key="port" :value="port">{{ port }}</option></select></label><label>Follower ID<input v-model.trim="form.followerId" /></label></div>
        <div class="two-columns"><label>Leader 串口<select v-model="form.leaderPort"><option v-for="port in ports" :key="port" :value="port">{{ port }}</option></select></label><label>Leader ID<input v-model.trim="form.leaderId" /></label></div>
        <div class="two-columns"><label>手眼相机<select v-model.number="form.cameraIndices[0]"><option v-for="camera in cameras" :key="camera.index" :value="camera.index">/dev/video{{ camera.index }}</option></select></label><label>固定相机<select v-model.number="form.cameraIndices[1]"><option v-for="camera in cameras" :key="camera.index" :value="camera.index">/dev/video{{ camera.index }}</option></select></label></div>
        <div class="three-columns"><label>Episodes<input v-model.number="form.numEpisodes" type="number" min="1" max="1000" /></label><label>单轮秒数<input v-model.number="form.episodeTime" type="number" min="1" max="3600" /></label><label>复位秒数<input v-model.number="form.resetTime" type="number" min="0" max="3600" /></label></div>
        <label>推理设备<select v-model="form.device"><option value="cpu">CPU</option><option value="cuda">CUDA</option></select></label>
      </div>
      <div class="safety-note">评估会独占机械臂和双摄像头；输出写入新的 Dataset，不覆盖训练数据。</div>
      <button class="primary" :disabled="creating || !formValid" @click="createEvaluation">{{ creating ? "创建中…" : "创建评估任务" }}</button>
    </section>

    <section class="evaluation-jobs" aria-label="模型评估任务列表">
      <div class="pane-heading"><div><p class="eyebrow">EVALUATIONS</p><h3>评估任务</h3></div><span>{{ runningJobs }} 运行中 / {{ jobs.length }} 总计</span></div>
      <div v-if="jobs.length" class="job-list"><button v-for="job in jobs" :key="job.id" :class="{ active: selectedJob?.id === job.id }" @click="selectedId = job.id"><i :class="job.state"></i><span><strong>{{ job.name }}</strong><small>{{ job.modelName }} v{{ job.modelVersion }} · {{ job.evalDataset }}</small></span><em :class="job.state">{{ evaluationState(job.state) }}</em></button></div>
      <div v-else class="empty">尚无评估任务</div>
    </section>

    <section class="evaluation-detail" aria-label="模型评估详情">
      <template v-if="selectedJob">
        <div class="job-title"><div><p class="eyebrow">{{ selectedJob.id }}</p><h3>{{ selectedJob.name }}</h3></div><span :class="['job-state', selectedJob.state]">{{ evaluationState(selectedJob.state) }}</span></div>
        <div class="facts"><span>{{ selectedJob.modelName }} v{{ selectedJob.modelVersion }}</span><span>{{ selectedJob.device.toUpperCase() }}</span><span>{{ selectedJob.numEpisodes }} Episodes</span><span>{{ selectedJob.episodeTime }}s / Episode</span></div>
        <dl><div><dt>评估 Dataset</dt><dd>{{ selectedJob.evalDataset }}</dd></div><div><dt>任务描述</dt><dd>{{ selectedJob.task }}</dd></div><div><dt>输出目录</dt><dd>{{ selectedJob.outputDatasetPath }}</dd></div><div><dt>设备映射</dt><dd>{{ selectedJob.followerPort }} / {{ selectedJob.leaderPort }} · video{{ selectedJob.cameraIndices[0] }} / video{{ selectedJob.cameraIndices[1] }}</dd></div></dl>
        <div class="actions"><button v-if="selectedJob.state === 'draft'" class="secondary" @click="deleteEvaluation(selectedJob.id)">删除草稿</button><button v-if="['draft','failed','cancelled'].includes(selectedJob.state)" :disabled="checking || runningJobs > 0" @click="startEvaluation(selectedJob.id)">▶ 启动评估</button><button v-if="selectedJob.state === 'running'" class="stop" @click="stopEvaluation(selectedJob.id)">■ 停止</button></div>
        <section class="preflight"><div><strong>评估前检查</strong><button :disabled="checking" @click="checkPreflight(selectedJob.id)">{{ checking ? "检查中…" : "重新检查" }}</button></div><ul v-if="preflight?.checks.length"><li v-for="check in preflight.checks" :key="check.id"><i :class="check.status"></i><span><strong>{{ check.label }}</strong><small>{{ check.detail }}</small></span></li></ul><p v-else>启动前检查模型、Dataset、串口、双摄像头、推理环境和设备占用</p></section>
        <div class="command"><div><strong>推理录制命令</strong><button @click="copyCommand">复制</button></div><code>{{ commandText }}</code></div>
        <div class="logs"><div><strong>评估日志</strong><span>{{ selectedJob.logs.length }} 行</span></div><pre>{{ selectedJob.logs.join("\n") || "任务尚未启动" }}</pre></div>
        <p v-if="selectedJob.error" class="job-error">{{ selectedJob.error }}</p>
      </template>
      <div v-else class="empty">选择一个评估任务查看详情</div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch } from "vue";

type ModelStage = "candidate" | "production" | "archived";
interface RegisteredModel { id: string; name: string; version: number; dataset: string; stage: ModelStage }
interface Camera { index: number; path: string }
type EvaluationState = "draft" | "running" | "stopping" | "completed" | "failed" | "cancelled";
interface EvaluationJob { id: string; name: string; modelId: string; modelName: string; modelVersion: number; evalDataset: string; task: string; followerPort: string; followerId: string; leaderPort: string; leaderId: string; cameraIndices: [number, number]; device: "cuda" | "cpu"; numEpisodes: number; episodeTime: number; resetTime: number; state: EvaluationState; createdAt: string; outputDatasetPath: string; command: string[]; error: string | null; logs: string[] }
interface PreflightCheck { id: string; label: string; status: "pass" | "warning" | "fail"; detail: string }
interface Preflight { ready: boolean; checks: PreflightCheck[]; checkedAt: string }

const emit = defineEmits<{ error: [message: string] }>();
const models = ref<RegisteredModel[]>([]); const jobs = ref<EvaluationJob[]>([]); const ports = ref<string[]>([]); const cameras = ref<Camera[]>([]);
const selectedId = ref(""); const creating = ref(false); const checking = ref(false); const preflight = ref<Preflight | null>(null);
let pollTimer: number | null = null;
const form = reactive({ name: "", modelId: "", evalDataset: "", task: "", followerPort: "", followerId: "R12253102", leaderPort: "", leaderId: "R07253102", cameraIndices: [-1, -1] as [number, number], device: "cpu" as "cuda" | "cpu", numEpisodes: 10, episodeTime: 30, resetTime: 10 });
const selectedJob = computed(() => jobs.value.find((job) => job.id === selectedId.value) || jobs.value[0] || null);
const selectedModel = computed(() => models.value.find((model) => model.id === form.modelId) || null);
const runningJobs = computed(() => jobs.value.filter((job) => ["running", "stopping"].includes(job.state)).length);
const formValid = computed(() => Boolean(form.name && selectedModel.value && form.evalDataset && form.evalDataset !== selectedModel.value?.dataset && form.task && form.followerPort && form.leaderPort && form.followerPort !== form.leaderPort && form.followerId && form.leaderId && form.cameraIndices[0] >= 0 && form.cameraIndices[1] >= 0 && form.cameraIndices[0] !== form.cameraIndices[1] && form.numEpisodes > 0 && form.episodeTime > 0 && form.resetTime >= 0));
const commandText = computed(() => selectedJob.value ? ["python", ...selectedJob.value.command].map(shellQuote).join(" ") : "");

async function requestJson(url: string, init?: RequestInit) { const response = await fetch(url, init); const data = await response.json(); if (!response.ok || data.ok === false) throw new Error(data.error || `HTTP ${response.status}`); return data; }
async function refreshJobs() { const data = await requestJson("/api/training/evaluations"); jobs.value = data.jobs || []; if (!jobs.value.some((job) => job.id === selectedId.value)) selectedId.value = jobs.value[0]?.id || ""; }
async function refreshAll() { try { const [modelData, jobData, portData, cameraData] = await Promise.all([requestJson("/api/training/models"), requestJson("/api/training/evaluations"), requestJson("/api/ports"), requestJson("/api/cameras")]); models.value = modelData.models || []; jobs.value = jobData.jobs || []; ports.value = portData.ports || []; cameras.value = cameraData.cameras || []; form.followerPort ||= ports.value[0] || ""; form.leaderPort ||= ports.value[1] || ""; form.cameraIndices = [cameraData.active?.camera ?? cameras.value[0]?.index ?? -1, cameraData.active?.camera2 ?? cameras.value[1]?.index ?? -1]; if (!form.modelId && models.value.length) { form.modelId = (models.value.find((model) => model.stage === "production") || models.value[0]).id; applyModelDefaults(); } if (!selectedId.value && jobs.value.length) selectedId.value = jobs.value[0].id; } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
function applyModelDefaults() { const model = selectedModel.value; if (!model) return; const suffix = `${model.name.replace(/[^A-Za-z0-9_-]+/g, "_")}_v${model.version}`; form.name ||= `eval_${suffix}`; form.evalDataset = `eval_${suffix}`.slice(0, 64); form.task ||= "Evaluate the robot policy"; }
async function createEvaluation() { if (!formValid.value || creating.value) return; creating.value = true; try { const data = await requestJson("/api/training/evaluations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); selectedId.value = data.job.id; await refreshJobs(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } finally { creating.value = false; } }
async function checkPreflight(id: string) { checking.value = true; try { preflight.value = await requestJson(`/api/training/evaluations/${encodeURIComponent(id)}/preflight`) as Preflight; return preflight.value.ready; } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); return false; } finally { checking.value = false; } }
async function startEvaluation(id: string) { const ready = await checkPreflight(id); if (!ready) { emit("error", "评估启动前检查未通过，请处理失败项后重试"); return; } try { await requestJson(`/api/training/evaluations/${encodeURIComponent(id)}/start`, { method: "POST" }); await refreshJobs(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
async function stopEvaluation(id: string) { try { await requestJson(`/api/training/evaluations/${encodeURIComponent(id)}/stop`, { method: "POST" }); await refreshJobs(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
async function deleteEvaluation(id: string) { try { await requestJson(`/api/training/evaluations/${encodeURIComponent(id)}`, { method: "DELETE" }); await refreshJobs(); } catch (cause) { emit("error", cause instanceof Error ? cause.message : String(cause)); } }
async function copyCommand() { if (commandText.value) await navigator.clipboard.writeText(commandText.value).catch(() => undefined); }
function shellQuote(value: string) { return /^[A-Za-z0-9_./:=,{}\[\]"-]+$/.test(value) ? value : `'${value.split("'").join("'\\''")}'`; }
function evaluationState(state: EvaluationState) { return ({ draft: "待启动", running: "评估中", stopping: "停止中", completed: "已完成", failed: "失败", cancelled: "已停止" })[state]; }
function modelStage(stage: ModelStage) { return ({ candidate: "候选", production: "生产", archived: "归档" })[stage]; }

watch(selectedId, () => { preflight.value = null; });
onMounted(() => { void refreshAll(); pollTimer = window.setInterval(() => { if (runningJobs.value) void refreshJobs(); }, 2000); });
onUnmounted(() => { if (pollTimer) window.clearInterval(pollTimer); });
</script>

<style scoped>
.evaluation-layout { display: grid; grid-template-columns: 330px 280px minmax(420px,1fr); min-height: calc(100vh - 225px); border: 1px solid rgba(151,188,222,.15); border-top: 0; background: #0d1928; }.evaluation-config,.evaluation-jobs,.evaluation-detail { min-width: 0; padding: 14px; }.evaluation-config,.evaluation-jobs { border-right: 1px solid rgba(151,188,222,.13); }.pane-heading,.job-title { display: flex; align-items: flex-start; justify-content: space-between; gap: 8px; margin-bottom: 14px; }.pane-heading h3,.job-title h3 { margin-top: 2px; font-size: 13px; }.pane-heading > span { color: #70899c; font-size: 8px; }.eyebrow { color: #78a9c6; font-size: 9px; font-weight: 700; letter-spacing: 1px; }.notice,.safety-note { margin-bottom: 9px; padding: 7px 8px; border-left: 2px solid #e1bf76; background: #282218; color: #d4b876; font-size: 8px; line-height: 1.5; }.safety-note { margin: 10px 0; border-left-color: #5a91ad; background: #102331; color: #86a7b9; }.form-grid { display: grid; gap: 8px; }.form-grid label { display: grid; gap: 4px; min-width: 0; color: #8ca2b3; font-size: 9px; }.form-grid input,.form-grid select,.form-grid textarea { width: 100%; min-width: 0; padding: 8px; border: 1px solid #29435f; border-radius: 4px; outline: 0; resize: vertical; background: #091522; color: #e7edf8; font: 9px sans-serif; }.two-columns,.three-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 7px; }.three-columns { grid-template-columns: repeat(3,1fr); }.primary { width: 100%; padding: 9px; border: 0; border-radius: 4px; cursor: pointer; background: #64c9e8; color: #07131c; font-size: 9px; font-weight: 650; }.primary:disabled { cursor: not-allowed; opacity: .4; }
.job-list { margin: 0 -14px; border-top: 1px solid rgba(151,188,222,.1); }.job-list button { display: grid; grid-template-columns: 8px 1fr auto; align-items: center; gap: 8px; width: 100%; padding: 11px 12px; border: 0; border-bottom: 1px solid rgba(151,188,222,.08); cursor: pointer; text-align: left; background: transparent; color: #dce8f2; }.job-list button:hover,.job-list button.active { background: #14283b; }.job-list i { width: 7px; height: 7px; border-radius: 50%; background: #718494; }.job-list i.running { background: #64c9e8; box-shadow: 0 0 8px #64c9e8; }.job-list i.completed { background: #54c994; }.job-list i.failed { background: #e86676; }.job-list span { display: grid; min-width: 0; gap: 3px; }.job-list strong,.job-list small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }.job-list strong { font-size: 9px; }.job-list small { color: #6f879a; font-size: 8px; }.job-list em,.job-state { padding: 3px 5px; border-radius: 3px; color: #879baa; background: #253443; font-size: 8px; font-style: normal; }.job-list em.running,.job-state.running { color: #8bdcf4; background: #17384a; }.job-list em.completed,.job-state.completed { color: #65daa4; background: #173a31; }.job-list em.failed,.job-state.failed { color: #ff91a0; background: #3a2028; }.job-list em.cancelled,.job-state.cancelled { color: #e1bf76; background: #3b321e; }
.facts { display: flex; flex-wrap: wrap; gap: 5px; margin-bottom: 12px; }.facts span { padding: 4px 6px; border-radius: 3px; background: #152638; color: #89a1b4; font: 8px ui-monospace,monospace; }.evaluation-detail dl { display: grid; gap: 5px; padding: 9px; background: #0a1622; }.evaluation-detail dl div { display: grid; grid-template-columns: 90px 1fr; gap: 8px; }.evaluation-detail dt { color: #647d90; font-size: 8px; }.evaluation-detail dd { overflow-wrap: anywhere; color: #a5b7c4; font-size: 8px; }.actions { display: flex; justify-content: flex-end; gap: 5px; margin: 9px 0; }.actions button { padding: 7px 11px; border: 0; border-radius: 4px; cursor: pointer; background: #64c9e8; color: #07131c; font-size: 9px; font-weight: 650; }.actions button.secondary { border: 1px solid #29435f; background: #101f2e; color: #8ea6b8; }.actions button.stop { background: #793746; color: #ffe8ec; }.actions button:disabled { opacity: .4; }
.preflight,.command,.logs { margin-top: 10px; border: 1px solid rgba(151,188,222,.13); background: #091522; }.preflight > div,.command > div,.logs > div { display: flex; align-items: center; justify-content: space-between; padding: 7px 9px; border-bottom: 1px solid rgba(151,188,222,.1); color: #8399aa; font-size: 8px; }.preflight button,.command button { border: 0; cursor: pointer; background: transparent; color: #76cdec; font-size: 8px; }.preflight ul { margin: 0; padding: 0; list-style: none; }.preflight li { display: grid; grid-template-columns: 7px 1fr; align-items: center; gap: 8px; padding: 7px 9px; border-top: 1px solid rgba(151,188,222,.07); }.preflight li i { width: 6px; height: 6px; border-radius: 50%; background: #54c994; }.preflight li i.warning { background: #e1bf76; }.preflight li i.fail { background: #e86676; }.preflight li span { display: grid; gap: 2px; }.preflight li strong { color: #a7bac6; font-size: 8px; }.preflight li small,.preflight p { color: #667f92; font-size: 8px; }.preflight p { margin: 0; padding: 10px 9px; }.command { background: #07111b; }.command code { display: block; max-height: 120px; overflow: auto; padding: 9px; color: #9fbdce; font: 8px/1.6 ui-monospace,monospace; white-space: pre-wrap; overflow-wrap: anywhere; }.logs { background: #07111b; }.logs pre { min-height: 170px; max-height: 320px; overflow: auto; margin: 0; padding: 9px; color: #91aa98; font: 8px/1.55 ui-monospace,monospace; white-space: pre-wrap; }.job-error { margin-top: 8px; color: #ff91a0; font-size: 9px; }.empty { display: grid; place-items: center; min-height: 180px; color: #667f92; font-size: 9px; }
@container (max-width: 1100px) { .evaluation-layout { grid-template-columns: 320px 1fr; }.evaluation-config { grid-row: 1/span 2; }.evaluation-jobs { border-right: 0; border-bottom: 1px solid rgba(151,188,222,.13); }.evaluation-detail { grid-column: 2; } }
@container (max-width: 720px) { .evaluation-layout { display: block; }.evaluation-config,.evaluation-jobs { border-right: 0; border-bottom: 1px solid rgba(151,188,222,.13); }.evaluation-detail { min-height: 360px; }.two-columns,.three-columns { grid-template-columns: 1fr; } }
</style>
